from enum import Enum


class ActionTable(Enum):
    CONNECTION_ACCEPTED_WHO_ARE_YOU = 0
    IDENTIFICATION = 1
    CONNECTION_ALLOWED = 2
    CONNECTION_REFUSED = 3
    IO_NOTIFICATION = 4
    REQUEST_IO_DATA = 5
    IO_RESPONSE_REQUEST = 6
    SYNC_TIME = 7
    PING = 8
    PONG = 9
    GET_IO_INFO = 10
    IO_INFO = 11
    SET_TRIGGER = 12
    TURN_ON_NOTIFICATION = 13
    TURN_OFF_NOTIFICATION = 14
    RESET_COUNTER = 15
    IO_ONLINE = 16
    IO_OFFLINE = 17
    IO_ERROR = 18
    SET_IO = 19
    START_DEBUG = 20
    DEBUG_INFO = 21
    STOP_DEBUG = 22
    ACK = 23
    NACK = 24
    SET_OUTPUT_CONFIGURATION = 25
    IO_SERVER_READY = 26
    IO_SERVER_RESTORED = 27
    INDEX_READY = 28
    PRINTER_RESPONSE = 29
    IO_STARTED = 30
    NEW_DATA = 31
    STATE_CODE = 32
    START_STREAM_FILE = 33
    FINISH_STREAM_FILE = 34
    STREAM_FILE = 35
    START_SEND_FILE_IO = 36
    PROGRESS_SEND_FILE_IO = 37
    FINISH_SEND_FILE_IO = 38
    ERROR_START_PLUGIN = 39
    PRINT = 49
    ERROR_SEND_FILE_IO = 40
    GET_FILE_FROM_IO = 41
    START_RECEIVE_FILE_FROM_IO = 42
    FINISH_RECEIVE_FILE_FROM_IO = 43
    PROGRESS_RECEIVE_FILE_FROM_IO = 44
    CANCEL_GET_FILE_FROM_IO = 45
    SAVE_FILE_FROM_IO = 46
    BRIDGE_SERVER_READY = 48
    PRINT_FILE = 49
    ERROR_PRINT_FILE = 50
    START_DOWNLOAD_FILE = 55
    FINISH_DOWNLOAD_FILE = 56
    DOWNLOAD_FILE = 53
    ERROR_DOWNLOAD_FILE = 57

    GET_SERVER_FILE_TREE = 58
    GET_REMOTE_FILE_TREE = 59
    SERVER_FILE_TREE = 60
    CLIENT_FILE_TREE = 61

    ERROR = 62

    DELETE_REMOTE_FILE = 63
    DELETE_REMOTE_DIRECTORY = 64

    STREAM_DIRECTORY = 65
    DOWNLOAD_DIRECTORY = 66

    PROGRESS_SEND_FILE = 67

    REMOTE_REBOOT = 69




